---
exclude: ^docs/arc-iac-docs/modules/  # externally managed by push from repos' documentation
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_docs
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
