site_name: "ARC"
site_description: "Main documentation for ARC"
repo_url: https://github.com/sourcefuse/arc-docs
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - techdocs-core
  - search
  - include-markdown
  - awesome-pages:
      filename: .pages.yml

docs_dir: docs

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sourcefuse/loopback4-microservice-catalog

copyright: |
  &copy; 2023 <a href="https://github.com/sourcefuse/arc-docs" target="_blank" rel="noopener">ARC</a>

# "nav:" configuration is moved to `.pages.yml` file in respective directories to utlize dynamic listing.
# See: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
