title: ARC IaC
nav:
  - Introduction: "README.md"
  - IaC Modules:
      - AWS:
          - Control Tower AFT: "arc-iac-docs/modules/terraform-aws-refarch-control-tower-aft"
          - Environment Bootstrap: "arc-iac-docs/modules/terraform-module-aws-bootstrap"
          - Network: "arc-iac-docs/modules/terraform-aws-ref-arch-network"
          - RDBMS: "arc-iac-docs/modules/terraform-aws-ref-arch-db"
          - ARC Lambda: "arc-iac-docs/modules/arc-lambda"
          - ARC CDK: "arc-iac-docs/modules/arc-cdk"
          - ECS: "arc-iac-docs/modules/terraform-aws-arc-ecs"
          - EKS: "arc-iac-docs/modules/terraform-aws-ref-arch-eks"
          - Tags: "arc-iac-docs/modules/terraform-aws-refarch-tags"
          - OpenSearch: "arc-iac-docs/modules/terraform-aws-refarch-opensearch"
          - TypeScript Lambda Boilerplate: "arc-iac-docs/modules/typescript-lambda-boilerplate"
          - Cloud Custodian: "arc-iac-docs/modules/terraform-aws-cloud-custodian"
          - CloudFront: "arc-iac-docs/modules/terraform-aws-refarch-cloudfront"
          - Healthcheck: "arc-iac-docs/modules/terraform-aws-arc-healthcheck"
          - KMS: "arc-iac-docs/modules/terraform-aws-arc-kms"
          - ARC Common Data: "arc-iac-docs/modules/terraform-aws-arc-common-data"
          - Waf: "arc-iac-docs/modules/terraform-aws-refarch-waf"
          - Vpn: "arc-iac-docs/modules/terraform-aws-refarch-vpn"
          - Workspaces: "arc-iac-docs/modules/terraform-aws-arc-workspace"
          - Postgres-Management: "arc-iac-docs/modules/terraform-postgresql-aws-arc-mgmt"
          - Security: "arc-iac-docs/modules/terraform-aws-arc-security"
          - Billing: "arc-iac-docs/modules/terraform-aws-arc-billing"
          - Document-DB: "arc-iac-docs/modules/terraform-aws-arc-document-db"
          - GitHub:
            - IAM: "arc-iac-docs/modules/terraform-aws-arc-github-iam"
            - Module Usage Guide: "arc-iac-docs/modules/terraform-aws-arc-github-iam/.docs/module-usage-guide"
          - Backstage:
            - ECS: "arc-iac-docs/modules/arc-backstage-ecs-app"
      - Cloud Native:
          - Kubernetes App: "arc-iac-docs/modules/terraform-k8s-app"
  - Reference Architectures:
      - AWS Account Baseline: "arc-iac-docs/reference_architectures/aws_account_baseline"
      - Control Tower and AFT: "arc-iac-docs/reference_architectures/control_tower_aft_setup"
      - Control Tower and LZA: "arc-iac-docs/reference_architectures/control_tower_lza_setup"
      - ARC IaC and LZA: "arc-iac-docs/reference_architectures/arc_iac_lza"
      - Network Baseline: "arc-iac-docs/reference_architectures/network_baseline"
      - ECS Platform Baseline: "arc-iac-docs/reference_architectures/ecs_platform_baseline"
      - EKS Platform Baseline: "arc-iac-docs/reference_architectures/eks_platform_baseline"
      - Lambda Platform Baseline: "arc-iac-docs/reference_architectures/lambda_platform_baseline"
      - Windows Basic Platform Baseline: "arc-iac-docs/reference_architectures/windows_basic_platform_baseline"
      - Windows Enterprise Platform Baseline: "arc-iac-docs/reference_architectures/windows_enterprise_platform_baseline"
